name: Run Claude Code

on:
  workflow_dispatch:  # Manually trigger from Actions tab

jobs:
  run-claude:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      issues: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create MCP Config
        run: |
          mkdir -p /tmp/mcp-config
          cat > /tmp/mcp-config/mcp-servers.json <<'EOF'
          {
            "mcpServers": {
              "cospec-matt-daemon": {
                "type": "http",
                "url": "https://sit.cospec.ai/mcp?deploymentId=e162d8dc-7cec-4b10-bfd8-cfb88e36dfc5",
                "headers": {
                  "x-auth-header": "${{ secrets.COSPEC_API_KEY }}",
                  "Content-Type": "application/json"
                }
              }
            }
          }
          EOF

      - name: Create Prompt File
        run: |
          mkdir -p /tmp/claude-prompts
          cat > /tmp/claude-prompts/task-prompt.txt <<'EOF'
          NOTE: When using mcp__cospec-matt-daemon_cospec_add_tools to add tools, you must use the mcp__cospec-matt-daemon_cospec_execute_tool with the new tool name as a param! :)

          We'd like you to add tools using the cospec tools first!!

          Progressively register tools for airtable, discover the github issues on there, find the slack message and reply to the thread with hello.

          In that order thanks xoxo
          EOF

      - name: Run Claude Code
        id: claude
        uses: anthropics/claude-code-base-action@beta
        with:
          prompt_file: /tmp/claude-prompts/task-prompt.txt
          allowed_tools: "mcp__cospec-matt-daemon"
          mcp_config: /tmp/mcp-config/mcp-servers.json
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          anthropic_model: claude-3-5-haiku-20241022