name: Cubes Task Agent

on:
  workflow_dispatch:
  issues:
    types: [opened, labeled]

jobs:
  run-cubes-agent:
    runs-on: ubuntu-latest
    if: github.event.issue.number == 22 || github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run Cubes Agent with Daemon
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MCP_SERVER_URL: https://mcp.cospec.ai/mcp?deploymentId=30501b5c-ae63-48be-a64a-bbdf4d7a52d7
        run: |
          echo "🤖 Cubes Agent starting work on issue #22..."
          echo "📡 Connected to Daemon: Cubes Task Agent"
          echo "🔗 GitHub Issue: https://github.com/jrnesc/empty/issues/22"

          # The agent will:
          # 1. Read the issue details from GitHub issue #22
          # 2. Analyze the requirements
          # 3. Implement the solution
          # 4. Create a PR with the implementation
          # 5. Update the Airtable status to "Done"

          npx -y @anthropics/claude-code \
            --api-key "$ANTHROPIC_API_KEY" \
            --mcp-server "$MCP_SERVER_URL" \
            --prompt "Complete the task in GitHub issue https://github.com/jrnesc/empty/issues/22. Read the issue, implement the solution, create a PR, and update the Airtable record status to 'In progress' first, then 'Done' when complete."
