name: Run Gemini CLI

on:
  workflow_dispatch:  # Manually trigger from Actions tab

jobs:
  run-gemini:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Gemini CLI
        id: gemini
        uses: google-github-actions/run-gemini-cli@v0.1.14
        with:
          gemini_api_key: ${{ secrets.GEMINI_API_KEY }}
          gemini_cli_version: 0.12.0-nightly.20251023.c4c0c0d1
          gemini_debug: true
          prompt: "NOTE: When using newly added tools, you must use the cospec_execute_tool with the new tool name as a param! :) We'd like you to register tools using the cospec tools first!! Reg tools for airtable discover the github issues on there, find the slack message and reply to the thread with hello. in that order thanks xoxo"
          gemini_model: gemini-2.5-pro
          settings: |
            {
              "mcpServers": {
                "cospec": {
                  "httpUrl": "https://sit.cospec.ai/mcp?deploymentId=e162d8dc-7cec-4b10-bfd8-cfb88e36dfc5",
                  "headers": {
                    "x-auth-header": "${{ secrets.COSPEC_API_KEY }}",
                    "Content-Type": "application/json"
                  },
                  "timeout": 5000
                }
              }
            }

      - name: Display Error JSON Files
        if: always()
        run: |
          echo "### Error Details" >> $GITHUB_STEP_SUMMARY
          ERROR_FILES=$(find /tmp -name "gemini-client-error-*.json" 2>/dev/null || true)
          if [ -n "$ERROR_FILES" ]; then
            for file in $ERROR_FILES; do
              echo "#### Error from: $file" >> $GITHUB_STEP_SUMMARY
              echo '```json' >> $GITHUB_STEP_SUMMARY
              cat "$file" >> $GITHUB_STEP_SUMMARY
              echo '```' >> $GITHUB_STEP_SUMMARY
              echo "" >> $GITHUB_STEP_SUMMARY
              echo "Full error file content:"
              cat "$file"
            done
          else
            echo "No error files found" >> $GITHUB_STEP_SUMMARY
          fi

      - name: Display Gemini Response
        if: always()
        run: |
          echo "### Gemini Response" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo "${{ steps.gemini.outputs.gemini_response }}" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

      - name: Display Errors
        if: always()
        run: |
          echo "### Gemini Errors (stderr)" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo "${{ steps.gemini.outputs.gemini_errors }}" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

      - name: Upload Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gemini-logs
          path: |
            gemini-artifacts/
            /tmp/gemini-client-error-*.json
          if-no-files-found: warn
